services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=app_user
      - DB_PASSWORD=app_pass
      - DB_NAME=app_db

  db:
    image: postgres:13
    container_name: app_postgres_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: app_db
    volumes:
      - ./persistencia/db/schema/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"